services:

  #  PostgreSQL (Database)
  postgres:
    image: postgres:15
    container_name: youshop-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: youshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #  Zookeeper (for Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: youshop-zookeeper
    restart: always
    ports:
      - "2181:2181"

  #  Kafka (Message Broker)
  kafka:
    image: wurstmeister/kafka:latest
    container_name: youshop-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  #  Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/auth?schema=public"
      KAFKA_BROKER: "kafka:9092"
    ports:
      - "3001:3000"

  #  Catalog Service
  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/catalog?schema=public"
      KAFKA_BROKER: "kafka:9092"
    ports:
      - "3002:3000"

  #  Inventory Service
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/inventory?schema=public"
      KAFKA_BROKER: "kafka:9092"
    ports:
      - "3003:3000"

  #  Orders Service
  orders-service:
    build: ./orders-service
    container_name: orders-service
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/orders?schema=public"
      KAFKA_BROKER: "kafka:9092"
    ports:
      - "3004:3000"

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - auth-service
      - catalog-service
      - inventory-service
      - orders-service
    environment:
      KAFKA_BROKER: "kafka:9092"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
